### ISSUE TITLE
Visualising graphs

### ISSUE THREAD

**Issue by katjabercic** [MathHubInfo/mhd#18]
**Notes**
We want to be able to show visualisations of objects, for some value of visualisations. 
People are attached to certain drawings, so storing coordinates (possibly multiple sets of such) for some graphs makes sense.

Erik says:
> Sage has quite a few built-in graphs and layouts for them, so one thing you could do to scrape drawings for existing graphs would be to check for isomorphism with any of Sage's built-in graphs and then steal their drawings if found (at import time, as you say).

**Tools, references**
- [Graph plotting in Sage with d3.js](http://doc.sagemath.org/html/en/reference/graphs/sage/graphs/graph_plot_js.html)
- [Sage built-in layouts for generic graphs](http://doc.sagemath.org/html/en/reference/graphs/sage/graphs/generic_graph.html#sage.graphs.generic_graph.GenericGraph.layout)
- [Sage layout algorithm implementation](https://gitlab.com/sagemath/sage/blob/b5c9cf037cbce672101725f269470135b9b2c5c4/src/sage/graphs/generic_graph.py#L5153)
- http://js.cytoscape.org/

**Comment by kohlhase** [comment]
we have that for one data set. close this issue?

**Comment by katjabercic** [comment]
It works for this dataset. Discussions with @tkw1536 and @embray revealed that it would be difficult to use the precomputed drawings of graphs from SageMath. The nice drawings there only come with using the right constructor. We would first need to determine which one. Perhaps we can revisit this at a later time.
