### ISSUE TITLE
The <title> of DataMathHub is still MathHubData

### ISSUE THREAD

**Issue by kohlhase** [MathHubInfo/mhd#29]
I think it should be `DataMathHub - <datasetname>` for the data sets and `DataMathHub` for the home screens. I guess other pages should have `DataMathHub - ???` accordingly.

**Comment by tkw1536** [comment]
We renamed everything to MathHubData (`mhd` for short) in 19536df0f6fca107f131ca0793aeea6651e14ebe.  I am seeing `MathHubData` as the project name whereas `data.mathhub.info` is the project url. I am hesitant to rename again, as I'd like to make sure the repository name (on e.g. GitHub, DockerHub and Travis), all variable / class names, database tables, and text strings are using the same abbreviation. Changing it again would be some effort.

**Comment by kohlhase** [comment]
This is starting to annoy me, We had talked about this multiple times, and at some point you had told me it must be DataMathHub and could not be different. and now we have published this name in multiple places, where we cannot change this any more. This will come over as very inconsistent, and hurt the system, the citation record, and ... 
By now I do not really care what the name is only that we use it consistently over the publication record.

**Comment by kohlhase** [comment]
I am not sure what to do here.

**Comment by tkw1536** [comment]
I guess I could rename the texts to DataMathHub short-term, and do the code renaming later on.

**Comment by tkw1536** [comment]
@kohlhase just brought this up again, he now suggested "MathDataHub". We should discuss this with @katjabercic.

**Comment by katjabercic** [comment]
I think that's ok.
