### ISSUE TITLE
Newlines break imports

### ISSUE THREAD

**Issue by jO-Osko** [MathHubInfo/mhd#75]
Nonempty string values with newline character `\n` break importing.

The problem arises because the string is directly copied to csv file and the newline character breaks the format.

Metadata file:
```json
{
    "displayName": "Newline example",
    "slug": "newline",
    "description": "",
    "url": "nope",
    "metadata": {
        "uri": ""
    },
    "properties": [
        {
            "slug": "text",
            "displayName": "text",
            "codec": "StandardString",
            "metadata": {
                "uri": "nope"
            }
        }
    ]
}
```

Data file
```
[
  [
    "Some text\nafter newline"
  ]
]
```

**Comment by tkw1536** [comment]
I believe this was fixed in https://github.com/MathHubInfo/mhd/commit/444533d8dca7c6f7e007c4e101d4a285c9f68eac
